//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silverlight_Patterns_in_Action
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    using Silverlight_Patterns_in_Action.Web;
    
    
    /// <summary>
    /// Context for the RIA application.
    /// </summary>
    /// <remarks>
    /// This context extends the base to make application services and types available
    /// for consumption from code and xaml.
    /// </remarks>
    public sealed partial class WebContext : WebContextBase
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the WebContext class.
        /// </summary>
        public WebContext()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the context that is registered as a lifetime object with the current application.
        /// </summary>
        /// <exception cref="InvalidOperationException"> is thrown if there is no current application,
        /// no contexts have been added, or more than one context has been added.
        /// </exception>
        /// <seealso cref="System.Windows.Application.ApplicationLifetimeObjects"/>
        public new static WebContext Current
        {
            get
            {
                return ((WebContext)(WebContextBase.Current));
            }
        }
        
        /// <summary>
        /// Gets a user representing the authenticated identity.
        /// </summary>
        public new User User
        {
            get
            {
                return ((User)(base.User));
            }
        }
    }
}
namespace Silverlight_Patterns_in_Action.Web
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.ServiceModel;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    using System.ServiceModel.Web;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// The domain context corresponding to the 'AuthenticationService' domain service.
    /// </summary>
    public sealed partial class AuthenticationContext : global::System.ServiceModel.DomainServices.Client.ApplicationServices.AuthenticationDomainContextBase
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationContext"/> class.
        /// </summary>
        public AuthenticationContext() : 
                this(new WebDomainClient<IAuthenticationServiceContract>(new Uri("Silverlight_Patterns_in_Action-Web-AuthenticationService.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationContext"/> class with the specified service URI.
        /// </summary>
        /// <param name="serviceUri">The AuthenticationService service URI.</param>
        public AuthenticationContext(Uri serviceUri) : 
                this(new WebDomainClient<IAuthenticationServiceContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationContext"/> class with the specified <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">The DomainClient instance to use for this domain context.</param>
        public AuthenticationContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the set of <see cref="User"/> entities that have been loaded into this <see cref="AuthenticationContext"/> instance.
        /// </summary>
        public EntitySet<User> Users
        {
            get
            {
                return base.EntityContainer.GetEntitySet<User>();
            }
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="User"/> entities using the 'GetUser' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="User"/> entities.</returns>
        public EntityQuery<User> GetUserQuery()
        {
            this.ValidateMethod("GetUserQuery", null);
            return base.CreateQuery<User>("GetUser", null, false, false);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="User"/> entities using the 'Login' query.
        /// </summary>
        /// <param name="userName">The value for the 'userName' parameter of the query.</param>
        /// <param name="password">The value for the 'password' parameter of the query.</param>
        /// <param name="isPersistent">The value for the 'isPersistent' parameter of the query.</param>
        /// <param name="customData">The value for the 'customData' parameter of the query.</param>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="User"/> entities.</returns>
        public EntityQuery<User> LoginQuery(string userName, string password, bool isPersistent, string customData)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("userName", userName);
            parameters.Add("password", password);
            parameters.Add("isPersistent", isPersistent);
            parameters.Add("customData", customData);
            this.ValidateMethod("LoginQuery", parameters);
            return base.CreateQuery<User>("Login", parameters, true, false);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="User"/> entities using the 'Logout' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="User"/> entities.</returns>
        public EntityQuery<User> LogoutQuery()
        {
            this.ValidateMethod("LogoutQuery", null);
            return base.CreateQuery<User>("Logout", null, true, false);
        }
        
        /// <summary>
        /// Creates a new entity container for this domain context's entity sets.
        /// </summary>
        /// <returns>A new container instance.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new AuthenticationContextEntityContainer();
        }
        
        /// <summary>
        /// Service contract for the 'AuthenticationService' domain service.
        /// </summary>
        [ServiceContract()]
        public interface IAuthenticationServiceContract
        {
            
            /// <summary>
            /// Asynchronously invokes the 'GetUser' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/AuthenticationService/GetUserDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/AuthenticationService/GetUser", ReplyAction="http://tempuri.org/AuthenticationService/GetUserResponse")]
            [WebGet()]
            IAsyncResult BeginGetUser(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetUser'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetUser'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetUser' operation.</returns>
            QueryResult<User> EndGetUser(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'Login' operation.
            /// </summary>
            /// <param name="userName">The value for the 'userName' parameter of this action.</param>
            /// <param name="password">The value for the 'password' parameter of this action.</param>
            /// <param name="isPersistent">The value for the 'isPersistent' parameter of this action.</param>
            /// <param name="customData">The value for the 'customData' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/AuthenticationService/LoginDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/AuthenticationService/Login", ReplyAction="http://tempuri.org/AuthenticationService/LoginResponse")]
            IAsyncResult BeginLogin(string userName, string password, bool isPersistent, string customData, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginLogin'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginLogin'.</param>
            /// <returns>The 'QueryResult' returned from the 'Login' operation.</returns>
            QueryResult<User> EndLogin(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'Logout' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/AuthenticationService/LogoutDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/AuthenticationService/Logout", ReplyAction="http://tempuri.org/AuthenticationService/LogoutResponse")]
            IAsyncResult BeginLogout(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginLogout'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginLogout'.</param>
            /// <returns>The 'QueryResult' returned from the 'Logout' operation.</returns>
            QueryResult<User> EndLogout(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'SubmitChanges' operation.
            /// </summary>
            /// <param name="changeSet">The change-set to submit.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/AuthenticationService/SubmitChangesDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/AuthenticationService/SubmitChanges", ReplyAction="http://tempuri.org/AuthenticationService/SubmitChangesResponse")]
            IAsyncResult BeginSubmitChanges(IEnumerable<ChangeSetEntry> changeSet, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginSubmitChanges'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginSubmitChanges'.</param>
            /// <returns>The collection of change-set entry elements returned from 'SubmitChanges'.</returns>
            IEnumerable<ChangeSetEntry> EndSubmitChanges(IAsyncResult result);
        }
        
        internal sealed class AuthenticationContextEntityContainer : EntityContainer
        {
            
            public AuthenticationContextEntityContainer()
            {
                this.CreateEntitySet<User>(EntitySetOperations.Edit);
            }
        }
    }
    
    /// <summary>
    /// The 'Category' entity class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/Silverlight_Patterns_in_Action.Web")]
    public sealed partial class Category : Entity
    {
        
        private int _categoryId;
        
        private string _categoryName;
        
        private string _description;
        
        private EntityCollection<Product> _products;
        
        private byte[] _version;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnCategoryIdChanging(int value);
        partial void OnCategoryIdChanged();
        partial void OnCategoryNameChanging(string value);
        partial void OnCategoryNameChanged();
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        partial void OnVersionChanging(byte[] value);
        partial void OnVersionChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Category"/> class.
        /// </summary>
        public Category()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'CategoryId' value.
        /// </summary>
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [RoundtripOriginal()]
        public int CategoryId
        {
            get
            {
                return this._categoryId;
            }
            set
            {
                if ((this._categoryId != value))
                {
                    this.OnCategoryIdChanging(value);
                    this.ValidateProperty("CategoryId", value);
                    this._categoryId = value;
                    this.RaisePropertyChanged("CategoryId");
                    this.OnCategoryIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'CategoryName' value.
        /// </summary>
        [DataMember()]
        [Required()]
        [StringLength(15)]
        public string CategoryName
        {
            get
            {
                return this._categoryName;
            }
            set
            {
                if ((this._categoryName != value))
                {
                    this.OnCategoryNameChanging(value);
                    this.RaiseDataMemberChanging("CategoryName");
                    this.ValidateProperty("CategoryName", value);
                    this._categoryName = value;
                    this.RaiseDataMemberChanged("CategoryName");
                    this.OnCategoryNameChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Description' value.
        /// </summary>
        [DataMember()]
        [Required()]
        [StringLength(100)]
        public string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                if ((this._description != value))
                {
                    this.OnDescriptionChanging(value);
                    this.RaiseDataMemberChanging("Description");
                    this.ValidateProperty("Description", value);
                    this._description = value;
                    this.RaiseDataMemberChanged("Description");
                    this.OnDescriptionChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets the collection of associated <see cref="Product"/> entities.
        /// </summary>
        [Association("Category_Product", "CategoryId", "CategoryId")]
        [XmlIgnore()]
        public EntityCollection<Product> Products
        {
            get
            {
                if ((this._products == null))
                {
                    this._products = new EntityCollection<Product>(this, "Products", this.FilterProducts, this.AttachProducts, this.DetachProducts);
                }
                return this._products;
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Version' value.
        /// </summary>
        [DataMember()]
        [Required()]
        public byte[] Version
        {
            get
            {
                return this._version;
            }
            set
            {
                if ((this._version != value))
                {
                    this.OnVersionChanging(value);
                    this.RaiseDataMemberChanging("Version");
                    this.ValidateProperty("Version", value);
                    this._version = value;
                    this.RaiseDataMemberChanged("Version");
                    this.OnVersionChanged();
                }
            }
        }
        
        private void AttachProducts(Product entity)
        {
            entity.Category = this;
        }
        
        private void DetachProducts(Product entity)
        {
            entity.Category = null;
        }
        
        private bool FilterProducts(Product entity)
        {
            return (entity.CategoryId == this.CategoryId);
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return this._categoryId;
        }
    }
    
    /// <summary>
    /// The 'Customer' entity class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/Silverlight_Patterns_in_Action.Web")]
    public sealed partial class Customer : Entity
    {
        
        private string _city;
        
        private string _companyName;
        
        private string _country;
        
        private int _customerId;
        
        private EntityCollection<Order> _orders;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        partial void OnCompanyNameChanging(string value);
        partial void OnCompanyNameChanged();
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        partial void OnCustomerIdChanging(int value);
        partial void OnCustomerIdChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Customer"/> class.
        /// </summary>
        public Customer()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'City' value.
        /// </summary>
        [DataMember()]
        [Required()]
        [StringLength(15)]
        public string City
        {
            get
            {
                return this._city;
            }
            set
            {
                if ((this._city != value))
                {
                    this.OnCityChanging(value);
                    this.RaiseDataMemberChanging("City");
                    this.ValidateProperty("City", value);
                    this._city = value;
                    this.RaiseDataMemberChanged("City");
                    this.OnCityChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'CompanyName' value.
        /// </summary>
        [DataMember()]
        [Required()]
        [StringLength(40)]
        public string CompanyName
        {
            get
            {
                return this._companyName;
            }
            set
            {
                if ((this._companyName != value))
                {
                    this.OnCompanyNameChanging(value);
                    this.RaiseDataMemberChanging("CompanyName");
                    this.ValidateProperty("CompanyName", value);
                    this._companyName = value;
                    this.RaiseDataMemberChanged("CompanyName");
                    this.OnCompanyNameChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Country' value.
        /// </summary>
        [DataMember()]
        [Required()]
        [StringLength(15)]
        public string Country
        {
            get
            {
                return this._country;
            }
            set
            {
                if ((this._country != value))
                {
                    this.OnCountryChanging(value);
                    this.RaiseDataMemberChanging("Country");
                    this.ValidateProperty("Country", value);
                    this._country = value;
                    this.RaiseDataMemberChanged("Country");
                    this.OnCountryChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'CustomerId' value.
        /// </summary>
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [RoundtripOriginal()]
        public int CustomerId
        {
            get
            {
                return this._customerId;
            }
            set
            {
                if ((this._customerId != value))
                {
                    this.OnCustomerIdChanging(value);
                    this.ValidateProperty("CustomerId", value);
                    this._customerId = value;
                    this.RaisePropertyChanged("CustomerId");
                    this.OnCustomerIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets the collection of associated <see cref="Order"/> entities.
        /// </summary>
        [Association("Customer_Order", "CustomerId", "CustomerId")]
        [XmlIgnore()]
        public EntityCollection<Order> Orders
        {
            get
            {
                if ((this._orders == null))
                {
                    this._orders = new EntityCollection<Order>(this, "Orders", this.FilterOrders, this.AttachOrders, this.DetachOrders);
                }
                return this._orders;
            }
        }
        
        private void AttachOrders(Order entity)
        {
            entity.Customer = this;
        }
        
        private void DetachOrders(Order entity)
        {
            entity.Customer = null;
        }
        
        private bool FilterOrders(Order entity)
        {
            return (entity.CustomerId == this.CustomerId);
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return this._customerId;
        }
    }
    
    /// <summary>
    /// The 'Order' entity class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/Silverlight_Patterns_in_Action.Web")]
    public sealed partial class Order : Entity
    {
        
        private EntityRef<Customer> _customer;
        
        private int _customerId;
        
        private Nullable<decimal> _freight;
        
        private DateTime _orderDate;
        
        private EntityCollection<OrderDetail> _orderDetails;
        
        private int _orderId;
        
        private Nullable<DateTime> _requiredDate;
        
        private Nullable<DateTime> _shippedDate;
        
        private byte[] _version;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnCustomerIdChanging(int value);
        partial void OnCustomerIdChanged();
        partial void OnFreightChanging(Nullable<decimal> value);
        partial void OnFreightChanged();
        partial void OnOrderDateChanging(DateTime value);
        partial void OnOrderDateChanged();
        partial void OnOrderIdChanging(int value);
        partial void OnOrderIdChanged();
        partial void OnRequiredDateChanging(Nullable<DateTime> value);
        partial void OnRequiredDateChanged();
        partial void OnShippedDateChanging(Nullable<DateTime> value);
        partial void OnShippedDateChanged();
        partial void OnVersionChanging(byte[] value);
        partial void OnVersionChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Order"/> class.
        /// </summary>
        public Order()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the associated <see cref="Customer"/> entity.
        /// </summary>
        [Association("Customer_Order", "CustomerId", "CustomerId", IsForeignKey=true)]
        [XmlIgnore()]
        public Customer Customer
        {
            get
            {
                if ((this._customer == null))
                {
                    this._customer = new EntityRef<Customer>(this, "Customer", this.FilterCustomer);
                }
                return this._customer.Entity;
            }
            set
            {
                Customer previous = this.Customer;
                if ((previous != value))
                {
                    this.ValidateProperty("Customer", value);
                    if ((previous != null))
                    {
                        this._customer.Entity = null;
                        previous.Orders.Remove(this);
                    }
                    if ((value != null))
                    {
                        this.CustomerId = value.CustomerId;
                    }
                    else
                    {
                        this.CustomerId = default(int);
                    }
                    this._customer.Entity = value;
                    if ((value != null))
                    {
                        value.Orders.Add(this);
                    }
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'CustomerId' value.
        /// </summary>
        [DataMember()]
        [RoundtripOriginal()]
        public int CustomerId
        {
            get
            {
                return this._customerId;
            }
            set
            {
                if ((this._customerId != value))
                {
                    this.OnCustomerIdChanging(value);
                    this.RaiseDataMemberChanging("CustomerId");
                    this.ValidateProperty("CustomerId", value);
                    this._customerId = value;
                    this.RaiseDataMemberChanged("CustomerId");
                    this.OnCustomerIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Freight' value.
        /// </summary>
        [DataMember()]
        public Nullable<decimal> Freight
        {
            get
            {
                return this._freight;
            }
            set
            {
                if ((this._freight != value))
                {
                    this.OnFreightChanging(value);
                    this.RaiseDataMemberChanging("Freight");
                    this.ValidateProperty("Freight", value);
                    this._freight = value;
                    this.RaiseDataMemberChanged("Freight");
                    this.OnFreightChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'OrderDate' value.
        /// </summary>
        [DataMember()]
        public DateTime OrderDate
        {
            get
            {
                return this._orderDate;
            }
            set
            {
                if ((this._orderDate != value))
                {
                    this.OnOrderDateChanging(value);
                    this.RaiseDataMemberChanging("OrderDate");
                    this.ValidateProperty("OrderDate", value);
                    this._orderDate = value;
                    this.RaiseDataMemberChanged("OrderDate");
                    this.OnOrderDateChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets the collection of associated <see cref="OrderDetail"/> entities.
        /// </summary>
        [Association("Order_OrderDetail", "OrderId", "OrderId")]
        [XmlIgnore()]
        public EntityCollection<OrderDetail> OrderDetails
        {
            get
            {
                if ((this._orderDetails == null))
                {
                    this._orderDetails = new EntityCollection<OrderDetail>(this, "OrderDetails", this.FilterOrderDetails, this.AttachOrderDetails, this.DetachOrderDetails);
                }
                return this._orderDetails;
            }
        }
        
        /// <summary>
        /// Gets or sets the 'OrderId' value.
        /// </summary>
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [RoundtripOriginal()]
        public int OrderId
        {
            get
            {
                return this._orderId;
            }
            set
            {
                if ((this._orderId != value))
                {
                    this.OnOrderIdChanging(value);
                    this.ValidateProperty("OrderId", value);
                    this._orderId = value;
                    this.RaisePropertyChanged("OrderId");
                    this.OnOrderIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'RequiredDate' value.
        /// </summary>
        [DataMember()]
        public Nullable<DateTime> RequiredDate
        {
            get
            {
                return this._requiredDate;
            }
            set
            {
                if ((this._requiredDate != value))
                {
                    this.OnRequiredDateChanging(value);
                    this.RaiseDataMemberChanging("RequiredDate");
                    this.ValidateProperty("RequiredDate", value);
                    this._requiredDate = value;
                    this.RaiseDataMemberChanged("RequiredDate");
                    this.OnRequiredDateChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'ShippedDate' value.
        /// </summary>
        [DataMember()]
        public Nullable<DateTime> ShippedDate
        {
            get
            {
                return this._shippedDate;
            }
            set
            {
                if ((this._shippedDate != value))
                {
                    this.OnShippedDateChanging(value);
                    this.RaiseDataMemberChanging("ShippedDate");
                    this.ValidateProperty("ShippedDate", value);
                    this._shippedDate = value;
                    this.RaiseDataMemberChanged("ShippedDate");
                    this.OnShippedDateChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Version' value.
        /// </summary>
        [DataMember()]
        [Required()]
        public byte[] Version
        {
            get
            {
                return this._version;
            }
            set
            {
                if ((this._version != value))
                {
                    this.OnVersionChanging(value);
                    this.RaiseDataMemberChanging("Version");
                    this.ValidateProperty("Version", value);
                    this._version = value;
                    this.RaiseDataMemberChanged("Version");
                    this.OnVersionChanged();
                }
            }
        }
        
        private bool FilterCustomer(Customer entity)
        {
            return (entity.CustomerId == this.CustomerId);
        }
        
        private void AttachOrderDetails(OrderDetail entity)
        {
            entity.Order = this;
        }
        
        private void DetachOrderDetails(OrderDetail entity)
        {
            entity.Order = null;
        }
        
        private bool FilterOrderDetails(OrderDetail entity)
        {
            return (entity.OrderId == this.OrderId);
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return this._orderId;
        }
    }
    
    /// <summary>
    /// The 'OrderDetail' entity class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/Silverlight_Patterns_in_Action.Web")]
    public sealed partial class OrderDetail : Entity
    {
        
        private double _discount;
        
        private EntityRef<Order> _order;
        
        private int _orderId;
        
        private EntityRef<Product> _product;
        
        private int _productId;
        
        private int _quantity;
        
        private decimal _unitPrice;
        
        private byte[] _version;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnDiscountChanging(double value);
        partial void OnDiscountChanged();
        partial void OnOrderIdChanging(int value);
        partial void OnOrderIdChanged();
        partial void OnProductIdChanging(int value);
        partial void OnProductIdChanged();
        partial void OnQuantityChanging(int value);
        partial void OnQuantityChanged();
        partial void OnUnitPriceChanging(decimal value);
        partial void OnUnitPriceChanged();
        partial void OnVersionChanging(byte[] value);
        partial void OnVersionChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderDetail"/> class.
        /// </summary>
        public OrderDetail()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'Discount' value.
        /// </summary>
        [DataMember()]
        public double Discount
        {
            get
            {
                return this._discount;
            }
            set
            {
                if ((this._discount != value))
                {
                    this.OnDiscountChanging(value);
                    this.RaiseDataMemberChanging("Discount");
                    this.ValidateProperty("Discount", value);
                    this._discount = value;
                    this.RaiseDataMemberChanged("Discount");
                    this.OnDiscountChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the associated <see cref="Order"/> entity.
        /// </summary>
        [Association("Order_OrderDetail", "OrderId", "OrderId", IsForeignKey=true)]
        [XmlIgnore()]
        public Order Order
        {
            get
            {
                if ((this._order == null))
                {
                    this._order = new EntityRef<Order>(this, "Order", this.FilterOrder);
                }
                return this._order.Entity;
            }
            set
            {
                Order previous = this.Order;
                if ((previous != value))
                {
                    this.ValidateProperty("Order", value);
                    if ((previous != null))
                    {
                        this._order.Entity = null;
                        previous.OrderDetails.Remove(this);
                    }
                    if ((value != null))
                    {
                        this.OrderId = value.OrderId;
                    }
                    else
                    {
                        this.OrderId = default(int);
                    }
                    this._order.Entity = value;
                    if ((value != null))
                    {
                        value.OrderDetails.Add(this);
                    }
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'OrderId' value.
        /// </summary>
        [DataMember()]
        [Key()]
        [RoundtripOriginal()]
        public int OrderId
        {
            get
            {
                return this._orderId;
            }
            set
            {
                if ((this._orderId != value))
                {
                    this.OnOrderIdChanging(value);
                    this.RaiseDataMemberChanging("OrderId");
                    this.ValidateProperty("OrderId", value);
                    this._orderId = value;
                    this.RaiseDataMemberChanged("OrderId");
                    this.OnOrderIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the associated <see cref="Product"/> entity.
        /// </summary>
        [Association("Product_OrderDetail", "ProductId", "ProductId", IsForeignKey=true)]
        [XmlIgnore()]
        public Product Product
        {
            get
            {
                if ((this._product == null))
                {
                    this._product = new EntityRef<Product>(this, "Product", this.FilterProduct);
                }
                return this._product.Entity;
            }
            set
            {
                Product previous = this.Product;
                if ((previous != value))
                {
                    this.ValidateProperty("Product", value);
                    if ((previous != null))
                    {
                        this._product.Entity = null;
                        previous.OrderDetails.Remove(this);
                    }
                    if ((value != null))
                    {
                        this.ProductId = value.ProductId;
                    }
                    else
                    {
                        this.ProductId = default(int);
                    }
                    this._product.Entity = value;
                    if ((value != null))
                    {
                        value.OrderDetails.Add(this);
                    }
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'ProductId' value.
        /// </summary>
        [DataMember()]
        [Key()]
        [RoundtripOriginal()]
        public int ProductId
        {
            get
            {
                return this._productId;
            }
            set
            {
                if ((this._productId != value))
                {
                    this.OnProductIdChanging(value);
                    this.RaiseDataMemberChanging("ProductId");
                    this.ValidateProperty("ProductId", value);
                    this._productId = value;
                    this.RaiseDataMemberChanged("ProductId");
                    this.OnProductIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Quantity' value.
        /// </summary>
        [DataMember()]
        public int Quantity
        {
            get
            {
                return this._quantity;
            }
            set
            {
                if ((this._quantity != value))
                {
                    this.OnQuantityChanging(value);
                    this.RaiseDataMemberChanging("Quantity");
                    this.ValidateProperty("Quantity", value);
                    this._quantity = value;
                    this.RaiseDataMemberChanged("Quantity");
                    this.OnQuantityChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'UnitPrice' value.
        /// </summary>
        [DataMember()]
        public decimal UnitPrice
        {
            get
            {
                return this._unitPrice;
            }
            set
            {
                if ((this._unitPrice != value))
                {
                    this.OnUnitPriceChanging(value);
                    this.RaiseDataMemberChanging("UnitPrice");
                    this.ValidateProperty("UnitPrice", value);
                    this._unitPrice = value;
                    this.RaiseDataMemberChanged("UnitPrice");
                    this.OnUnitPriceChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Version' value.
        /// </summary>
        [DataMember()]
        [Required()]
        public byte[] Version
        {
            get
            {
                return this._version;
            }
            set
            {
                if ((this._version != value))
                {
                    this.OnVersionChanging(value);
                    this.RaiseDataMemberChanging("Version");
                    this.ValidateProperty("Version", value);
                    this._version = value;
                    this.RaiseDataMemberChanged("Version");
                    this.OnVersionChanged();
                }
            }
        }
        
        private bool FilterOrder(Order entity)
        {
            return (entity.OrderId == this.OrderId);
        }
        
        private bool FilterProduct(Product entity)
        {
            return (entity.ProductId == this.ProductId);
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return EntityKey.Create(this._orderId, this._productId);
        }
    }
    
    /// <summary>
    /// The 'Product' entity class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/Silverlight_Patterns_in_Action.Web")]
    public sealed partial class Product : Entity
    {
        
        private EntityRef<Category> _category;
        
        private int _categoryId;
        
        private EntityCollection<OrderDetail> _orderDetails;
        
        private int _productId;
        
        private string _productName;
        
        private decimal _unitPrice;
        
        private int _unitsInStock;
        
        private byte[] _version;
        
        private string _weight;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnCategoryIdChanging(int value);
        partial void OnCategoryIdChanged();
        partial void OnProductIdChanging(int value);
        partial void OnProductIdChanged();
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        partial void OnUnitPriceChanging(decimal value);
        partial void OnUnitPriceChanged();
        partial void OnUnitsInStockChanging(int value);
        partial void OnUnitsInStockChanged();
        partial void OnVersionChanging(byte[] value);
        partial void OnVersionChanged();
        partial void OnWeightChanging(string value);
        partial void OnWeightChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Product"/> class.
        /// </summary>
        public Product()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the associated <see cref="Category"/> entity.
        /// </summary>
        [Association("Category_Product", "CategoryId", "CategoryId", IsForeignKey=true)]
        [XmlIgnore()]
        public Category Category
        {
            get
            {
                if ((this._category == null))
                {
                    this._category = new EntityRef<Category>(this, "Category", this.FilterCategory);
                }
                return this._category.Entity;
            }
            set
            {
                Category previous = this.Category;
                if ((previous != value))
                {
                    this.ValidateProperty("Category", value);
                    if ((previous != null))
                    {
                        this._category.Entity = null;
                        previous.Products.Remove(this);
                    }
                    if ((value != null))
                    {
                        this.CategoryId = value.CategoryId;
                    }
                    else
                    {
                        this.CategoryId = default(int);
                    }
                    this._category.Entity = value;
                    if ((value != null))
                    {
                        value.Products.Add(this);
                    }
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'CategoryId' value.
        /// </summary>
        [DataMember()]
        [RoundtripOriginal()]
        public int CategoryId
        {
            get
            {
                return this._categoryId;
            }
            set
            {
                if ((this._categoryId != value))
                {
                    this.OnCategoryIdChanging(value);
                    this.RaiseDataMemberChanging("CategoryId");
                    this.ValidateProperty("CategoryId", value);
                    this._categoryId = value;
                    this.RaiseDataMemberChanged("CategoryId");
                    this.OnCategoryIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets the collection of associated <see cref="OrderDetail"/> entities.
        /// </summary>
        [Association("Product_OrderDetail", "ProductId", "ProductId")]
        [XmlIgnore()]
        public EntityCollection<OrderDetail> OrderDetails
        {
            get
            {
                if ((this._orderDetails == null))
                {
                    this._orderDetails = new EntityCollection<OrderDetail>(this, "OrderDetails", this.FilterOrderDetails, this.AttachOrderDetails, this.DetachOrderDetails);
                }
                return this._orderDetails;
            }
        }
        
        /// <summary>
        /// Gets or sets the 'ProductId' value.
        /// </summary>
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [RoundtripOriginal()]
        public int ProductId
        {
            get
            {
                return this._productId;
            }
            set
            {
                if ((this._productId != value))
                {
                    this.OnProductIdChanging(value);
                    this.ValidateProperty("ProductId", value);
                    this._productId = value;
                    this.RaisePropertyChanged("ProductId");
                    this.OnProductIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'ProductName' value.
        /// </summary>
        [DataMember()]
        [Required()]
        [StringLength(40)]
        public string ProductName
        {
            get
            {
                return this._productName;
            }
            set
            {
                if ((this._productName != value))
                {
                    this.OnProductNameChanging(value);
                    this.RaiseDataMemberChanging("ProductName");
                    this.ValidateProperty("ProductName", value);
                    this._productName = value;
                    this.RaiseDataMemberChanged("ProductName");
                    this.OnProductNameChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'UnitPrice' value.
        /// </summary>
        [DataMember()]
        public decimal UnitPrice
        {
            get
            {
                return this._unitPrice;
            }
            set
            {
                if ((this._unitPrice != value))
                {
                    this.OnUnitPriceChanging(value);
                    this.RaiseDataMemberChanging("UnitPrice");
                    this.ValidateProperty("UnitPrice", value);
                    this._unitPrice = value;
                    this.RaiseDataMemberChanged("UnitPrice");
                    this.OnUnitPriceChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'UnitsInStock' value.
        /// </summary>
        [DataMember()]
        public int UnitsInStock
        {
            get
            {
                return this._unitsInStock;
            }
            set
            {
                if ((this._unitsInStock != value))
                {
                    this.OnUnitsInStockChanging(value);
                    this.RaiseDataMemberChanging("UnitsInStock");
                    this.ValidateProperty("UnitsInStock", value);
                    this._unitsInStock = value;
                    this.RaiseDataMemberChanged("UnitsInStock");
                    this.OnUnitsInStockChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Version' value.
        /// </summary>
        [DataMember()]
        [Required()]
        public byte[] Version
        {
            get
            {
                return this._version;
            }
            set
            {
                if ((this._version != value))
                {
                    this.OnVersionChanging(value);
                    this.RaiseDataMemberChanging("Version");
                    this.ValidateProperty("Version", value);
                    this._version = value;
                    this.RaiseDataMemberChanged("Version");
                    this.OnVersionChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Weight' value.
        /// </summary>
        [DataMember()]
        [Required()]
        [StringLength(20)]
        public string Weight
        {
            get
            {
                return this._weight;
            }
            set
            {
                if ((this._weight != value))
                {
                    this.OnWeightChanging(value);
                    this.RaiseDataMemberChanging("Weight");
                    this.ValidateProperty("Weight", value);
                    this._weight = value;
                    this.RaiseDataMemberChanged("Weight");
                    this.OnWeightChanged();
                }
            }
        }
        
        private bool FilterCategory(Category entity)
        {
            return (entity.CategoryId == this.CategoryId);
        }
        
        private void AttachOrderDetails(OrderDetail entity)
        {
            entity.Product = this;
        }
        
        private void DetachOrderDetails(OrderDetail entity)
        {
            entity.Product = null;
        }
        
        private bool FilterOrderDetails(OrderDetail entity)
        {
            return (entity.ProductId == this.ProductId);
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return this._productId;
        }
    }
    
    /// <summary>
    /// The 'User' entity class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/Silverlight_Patterns_in_Action.Web")]
    public sealed partial class User : Entity, global::System.Security.Principal.IIdentity, global::System.Security.Principal.IPrincipal
    {
        
        private string _friendlyName;
        
        private string _name = string.Empty;
        
        private IEnumerable<string> _roles;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnFriendlyNameChanging(string value);
        partial void OnFriendlyNameChanged();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        partial void OnRolesChanging(IEnumerable<string> value);
        partial void OnRolesChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="User"/> class.
        /// </summary>
        public User()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'FriendlyName' value.
        /// </summary>
        [DataMember()]
        public string FriendlyName
        {
            get
            {
                return this._friendlyName;
            }
            set
            {
                if ((this._friendlyName != value))
                {
                    this.OnFriendlyNameChanging(value);
                    this.RaiseDataMemberChanging("FriendlyName");
                    this.ValidateProperty("FriendlyName", value);
                    this._friendlyName = value;
                    this.RaiseDataMemberChanged("FriendlyName");
                    this.OnFriendlyNameChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Name' value.
        /// </summary>
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [RoundtripOriginal()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                if ((this._name != value))
                {
                    this.OnNameChanging(value);
                    this.ValidateProperty("Name", value);
                    this._name = value;
                    this.RaisePropertyChanged("Name");
                    this.OnNameChanged();
                    this.RaisePropertyChanged("IsAuthenticated");
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Roles' value.
        /// </summary>
        [DataMember()]
        [Editable(false)]
        public IEnumerable<string> Roles
        {
            get
            {
                return this._roles;
            }
            set
            {
                if ((this._roles != value))
                {
                    this.OnRolesChanging(value);
                    this.ValidateProperty("Roles", value);
                    this._roles = value;
                    this.RaisePropertyChanged("Roles");
                    this.OnRolesChanged();
                }
            }
        }
        
        string global::System.Security.Principal.IIdentity.AuthenticationType
        {
            get
            {
                return string.Empty;
            }
        }
        
        /// <summary>
        /// Gets a value indicating whether the identity is authenticated.
        /// </summary>
        /// <remarks>
        /// This value is <c>true</c> if <see cref="Name"/> is not <c>null</c> or empty.
        /// </remarks>
        public bool IsAuthenticated
        {
            get
            {
                return (true != string.IsNullOrEmpty(this.Name));
            }
        }
        
        string global::System.Security.Principal.IIdentity.Name
        {
            get
            {
                return this.Name;
            }
        }
        
        global::System.Security.Principal.IIdentity global::System.Security.Principal.IPrincipal.Identity
        {
            get
            {
                return this;
            }
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return this._name;
        }
        
        /// <summary>
        /// Return whether the principal is in the role.
        /// </summary>
        /// <remarks>
        /// Returns whether the specified role is contained in the roles.
        /// This implementation is case sensitive.
        /// </remarks>
        /// <param name="role">The name of the role for which to check membership.</param>
        /// <returns>Whether the principal is in the role.</returns>
        public bool IsInRole(string role)
        {
            if ((this.Roles == null))
            {
                return false;
            }
            return global::System.Linq.Enumerable.Contains(this.Roles, role);
        }
    }
}
namespace Silverlight_Patterns_in_Action.Web.Services.Web
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    using System.ServiceModel.Web;
    using Silverlight_Patterns_in_Action.Web;
    
    
    /// <summary>
    /// The domain context corresponding to the 'ActionDomainService' domain service.
    /// </summary>
    public sealed partial class ActionDomainContext : DomainContext
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ActionDomainContext"/> class.
        /// </summary>
        public ActionDomainContext() : 
                this(new WebDomainClient<IActionDomainServiceContract>(new Uri("Silverlight_Patterns_in_Action-Web-Services-Web-ActionDomainService.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ActionDomainContext"/> class with the specified service URI.
        /// </summary>
        /// <param name="serviceUri">The ActionDomainService service URI.</param>
        public ActionDomainContext(Uri serviceUri) : 
                this(new WebDomainClient<IActionDomainServiceContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ActionDomainContext"/> class with the specified <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">The DomainClient instance to use for this domain context.</param>
        public ActionDomainContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the set of <see cref="Customer"/> entities that have been loaded into this <see cref="ActionDomainContext"/> instance.
        /// </summary>
        public EntitySet<Customer> Customers
        {
            get
            {
                return base.EntityContainer.GetEntitySet<Customer>();
            }
        }
        
        /// <summary>
        /// Gets the set of <see cref="Product"/> entities that have been loaded into this <see cref="ActionDomainContext"/> instance.
        /// </summary>
        public EntitySet<Product> Products
        {
            get
            {
                return base.EntityContainer.GetEntitySet<Product>();
            }
        }
        
        /// <summary>
        /// Gets the set of <see cref="Category"/> entities that have been loaded into this <see cref="ActionDomainContext"/> instance.
        /// </summary>
        public EntitySet<Category> Categories
        {
            get
            {
                return base.EntityContainer.GetEntitySet<Category>();
            }
        }
        
        /// <summary>
        /// Gets the set of <see cref="OrderDetail"/> entities that have been loaded into this <see cref="ActionDomainContext"/> instance.
        /// </summary>
        public EntitySet<OrderDetail> OrderDetails
        {
            get
            {
                return base.EntityContainer.GetEntitySet<OrderDetail>();
            }
        }
        
        /// <summary>
        /// Gets the set of <see cref="Order"/> entities that have been loaded into this <see cref="ActionDomainContext"/> instance.
        /// </summary>
        public EntitySet<Order> Orders
        {
            get
            {
                return base.EntityContainer.GetEntitySet<Order>();
            }
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Customer"/> entities using the 'FindCustomers' query.
        /// </summary>
        /// <param name="name">The value for the 'name' parameter of the query.</param>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Customer"/> entities.</returns>
        public EntityQuery<Customer> FindCustomersQuery(string name)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("name", name);
            this.ValidateMethod("FindCustomersQuery", parameters);
            return base.CreateQuery<Customer>("FindCustomers", parameters, false, true);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Product"/> entities using the 'FindProducts' query.
        /// </summary>
        /// <param name="productName">The value for the 'productName' parameter of the query.</param>
        /// <param name="fromPrice">The value for the 'fromPrice' parameter of the query.</param>
        /// <param name="thruPrice">The value for the 'thruPrice' parameter of the query.</param>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Product"/> entities.</returns>
        public EntityQuery<Product> FindProductsQuery(string productName, Nullable<double> fromPrice, Nullable<double> thruPrice)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("productName", productName);
            parameters.Add("fromPrice", fromPrice);
            parameters.Add("thruPrice", thruPrice);
            this.ValidateMethod("FindProductsQuery", parameters);
            return base.CreateQuery<Product>("FindProducts", parameters, false, true);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Category"/> entities using the 'GetCategories' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Category"/> entities.</returns>
        public EntityQuery<Category> GetCategoriesQuery()
        {
            this.ValidateMethod("GetCategoriesQuery", null);
            return base.CreateQuery<Category>("GetCategories", null, false, true);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Customer"/> entities using the 'GetCustomers' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Customer"/> entities.</returns>
        public EntityQuery<Customer> GetCustomersQuery()
        {
            this.ValidateMethod("GetCustomersQuery", null);
            return base.CreateQuery<Customer>("GetCustomers", null, false, true);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="OrderDetail"/> entities using the 'GetOrderDetailsByOrder' query.
        /// </summary>
        /// <param name="orderId">The value for the 'orderId' parameter of the query.</param>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="OrderDetail"/> entities.</returns>
        public EntityQuery<OrderDetail> GetOrderDetailsByOrderQuery(int orderId)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("orderId", orderId);
            this.ValidateMethod("GetOrderDetailsByOrderQuery", parameters);
            return base.CreateQuery<OrderDetail>("GetOrderDetailsByOrder", parameters, false, true);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Order"/> entities using the 'GetOrders' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Order"/> entities.</returns>
        public EntityQuery<Order> GetOrdersQuery()
        {
            this.ValidateMethod("GetOrdersQuery", null);
            return base.CreateQuery<Order>("GetOrders", null, false, true);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Order"/> entities using the 'GetOrdersByCustomer' query.
        /// </summary>
        /// <param name="customerId">The value for the 'customerId' parameter of the query.</param>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Order"/> entities.</returns>
        public EntityQuery<Order> GetOrdersByCustomerQuery(int customerId)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("customerId", customerId);
            this.ValidateMethod("GetOrdersByCustomerQuery", parameters);
            return base.CreateQuery<Order>("GetOrdersByCustomer", parameters, false, true);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Order"/> entities using the 'GetOrdersByYear' query.
        /// </summary>
        /// <param name="year">The value for the 'year' parameter of the query.</param>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Order"/> entities.</returns>
        public EntityQuery<Order> GetOrdersByYearQuery(int year)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("year", year);
            this.ValidateMethod("GetOrdersByYearQuery", parameters);
            return base.CreateQuery<Order>("GetOrdersByYear", parameters, false, true);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Product"/> entities using the 'GetProductsByCategory' query.
        /// </summary>
        /// <param name="categoryId">The value for the 'categoryId' parameter of the query.</param>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Product"/> entities.</returns>
        public EntityQuery<Product> GetProductsByCategoryQuery(int categoryId)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("categoryId", categoryId);
            this.ValidateMethod("GetProductsByCategoryQuery", parameters);
            return base.CreateQuery<Product>("GetProductsByCategory", parameters, false, true);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetOrderCountByCustomer' method of the domain service.
        /// </summary>
        /// <param name="customerId">The value for the 'customerId' parameter of this action.</param>
        /// <param name="callback">Callback to invoke when the operation completes.</param>
        /// <param name="userState">Value to pass to the callback.  It can be <c>null</c>.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<int> GetOrderCountByCustomer(int customerId, Action<InvokeOperation<int>> callback, object userState)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("customerId", customerId);
            this.ValidateMethod("GetOrderCountByCustomer", parameters);
            return ((InvokeOperation<int>)(this.InvokeOperation("GetOrderCountByCustomer", typeof(int), parameters, true, callback, userState)));
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetOrderCountByCustomer' method of the domain service.
        /// </summary>
        /// <param name="customerId">The value for the 'customerId' parameter of this action.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<int> GetOrderCountByCustomer(int customerId)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("customerId", customerId);
            this.ValidateMethod("GetOrderCountByCustomer", parameters);
            return ((InvokeOperation<int>)(this.InvokeOperation("GetOrderCountByCustomer", typeof(int), parameters, true, null, null)));
        }
        
        /// <summary>
        /// Creates a new entity container for this domain context's entity sets.
        /// </summary>
        /// <returns>A new container instance.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new ActionDomainContextEntityContainer();
        }
        
        /// <summary>
        /// Service contract for the 'ActionDomainService' domain service.
        /// </summary>
        [ServiceContract()]
        public interface IActionDomainServiceContract
        {
            
            /// <summary>
            /// Asynchronously invokes the 'FindCustomers' operation.
            /// </summary>
            /// <param name="name">The value for the 'name' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/ActionDomainService/FindCustomersDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/ActionDomainService/FindCustomers", ReplyAction="http://tempuri.org/ActionDomainService/FindCustomersResponse")]
            [WebGet()]
            IAsyncResult BeginFindCustomers(string name, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginFindCustomers'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginFindCustomers'.</param>
            /// <returns>The 'QueryResult' returned from the 'FindCustomers' operation.</returns>
            QueryResult<Customer> EndFindCustomers(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'FindProducts' operation.
            /// </summary>
            /// <param name="productName">The value for the 'productName' parameter of this action.</param>
            /// <param name="fromPrice">The value for the 'fromPrice' parameter of this action.</param>
            /// <param name="thruPrice">The value for the 'thruPrice' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/ActionDomainService/FindProductsDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/ActionDomainService/FindProducts", ReplyAction="http://tempuri.org/ActionDomainService/FindProductsResponse")]
            [WebGet()]
            IAsyncResult BeginFindProducts(string productName, Nullable<double> fromPrice, Nullable<double> thruPrice, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginFindProducts'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginFindProducts'.</param>
            /// <returns>The 'QueryResult' returned from the 'FindProducts' operation.</returns>
            QueryResult<Product> EndFindProducts(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetCategories' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/ActionDomainService/GetCategoriesDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/ActionDomainService/GetCategories", ReplyAction="http://tempuri.org/ActionDomainService/GetCategoriesResponse")]
            [WebGet()]
            IAsyncResult BeginGetCategories(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetCategories'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetCategories'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetCategories' operation.</returns>
            QueryResult<Category> EndGetCategories(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetCustomers' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/ActionDomainService/GetCustomersDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/ActionDomainService/GetCustomers", ReplyAction="http://tempuri.org/ActionDomainService/GetCustomersResponse")]
            [WebGet()]
            IAsyncResult BeginGetCustomers(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetCustomers'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetCustomers'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetCustomers' operation.</returns>
            QueryResult<Customer> EndGetCustomers(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetOrderCountByCustomer' operation.
            /// </summary>
            /// <param name="customerId">The value for the 'customerId' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/ActionDomainService/GetOrderCountByCustomerDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/ActionDomainService/GetOrderCountByCustomer", ReplyAction="http://tempuri.org/ActionDomainService/GetOrderCountByCustomerResponse")]
            IAsyncResult BeginGetOrderCountByCustomer(int customerId, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetOrderCountByCustomer'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetOrderCountByCustomer'.</param>
            /// <returns>The 'Int32' returned from the 'GetOrderCountByCustomer' operation.</returns>
            int EndGetOrderCountByCustomer(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetOrderDetailsByOrder' operation.
            /// </summary>
            /// <param name="orderId">The value for the 'orderId' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/ActionDomainService/GetOrderDetailsByOrderDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/ActionDomainService/GetOrderDetailsByOrder", ReplyAction="http://tempuri.org/ActionDomainService/GetOrderDetailsByOrderResponse")]
            [WebGet()]
            IAsyncResult BeginGetOrderDetailsByOrder(int orderId, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetOrderDetailsByOrder'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetOrderDetailsByOrder'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetOrderDetailsByOrder' operation.</returns>
            QueryResult<OrderDetail> EndGetOrderDetailsByOrder(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetOrders' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/ActionDomainService/GetOrdersDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/ActionDomainService/GetOrders", ReplyAction="http://tempuri.org/ActionDomainService/GetOrdersResponse")]
            [WebGet()]
            IAsyncResult BeginGetOrders(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetOrders'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetOrders'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetOrders' operation.</returns>
            QueryResult<Order> EndGetOrders(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetOrdersByCustomer' operation.
            /// </summary>
            /// <param name="customerId">The value for the 'customerId' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/ActionDomainService/GetOrdersByCustomerDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/ActionDomainService/GetOrdersByCustomer", ReplyAction="http://tempuri.org/ActionDomainService/GetOrdersByCustomerResponse")]
            [WebGet()]
            IAsyncResult BeginGetOrdersByCustomer(int customerId, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetOrdersByCustomer'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetOrdersByCustomer'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetOrdersByCustomer' operation.</returns>
            QueryResult<Order> EndGetOrdersByCustomer(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetOrdersByYear' operation.
            /// </summary>
            /// <param name="year">The value for the 'year' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/ActionDomainService/GetOrdersByYearDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/ActionDomainService/GetOrdersByYear", ReplyAction="http://tempuri.org/ActionDomainService/GetOrdersByYearResponse")]
            [WebGet()]
            IAsyncResult BeginGetOrdersByYear(int year, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetOrdersByYear'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetOrdersByYear'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetOrdersByYear' operation.</returns>
            QueryResult<Order> EndGetOrdersByYear(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetProductsByCategory' operation.
            /// </summary>
            /// <param name="categoryId">The value for the 'categoryId' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/ActionDomainService/GetProductsByCategoryDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/ActionDomainService/GetProductsByCategory", ReplyAction="http://tempuri.org/ActionDomainService/GetProductsByCategoryResponse")]
            [WebGet()]
            IAsyncResult BeginGetProductsByCategory(int categoryId, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetProductsByCategory'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetProductsByCategory'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetProductsByCategory' operation.</returns>
            QueryResult<Product> EndGetProductsByCategory(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'SubmitChanges' operation.
            /// </summary>
            /// <param name="changeSet">The change-set to submit.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/ActionDomainService/SubmitChangesDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/ActionDomainService/SubmitChanges", ReplyAction="http://tempuri.org/ActionDomainService/SubmitChangesResponse")]
            IAsyncResult BeginSubmitChanges(IEnumerable<ChangeSetEntry> changeSet, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginSubmitChanges'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginSubmitChanges'.</param>
            /// <returns>The collection of change-set entry elements returned from 'SubmitChanges'.</returns>
            IEnumerable<ChangeSetEntry> EndSubmitChanges(IAsyncResult result);
        }
        
        internal sealed class ActionDomainContextEntityContainer : EntityContainer
        {
            
            public ActionDomainContextEntityContainer()
            {
                this.CreateEntitySet<Category>(EntitySetOperations.None);
                this.CreateEntitySet<Customer>(EntitySetOperations.All);
                this.CreateEntitySet<Order>(EntitySetOperations.None);
                this.CreateEntitySet<OrderDetail>(EntitySetOperations.None);
                this.CreateEntitySet<Product>(EntitySetOperations.None);
            }
        }
    }
}
